account/urls.py
from django.shortcuts import render
from django.urls import path

from . import views

app_name = "account"

urlpatterns = [
    path("registration/", render, kwargs={"template_name": "registration.html"}, name='registration'),
    path("reg/", views.register_user),
    path("reg_succ/", render, kwargs={"template_name": "reg_succ.html"}, name='reg_succ'),
    path("reg_err/", render, kwargs={"template_name": "reg_err.html"}, name='reg_err'),
]

beauty_city/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include

from salons import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", render, kwargs={"template_name": "index.html"}, name="start_page"),
    path('service/', views.service, name='service'),
    path('service_finaly/', views.service_finaly, name='service_finaly'),
    path('popup/', views.popup, name='popup'),
    path('profile/', views.profile, name='profile'),
    path('notes/', views.notes, name='notes'),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('account.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT) +  \
                   static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/admin.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Beauty City</title>
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;700&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css" integrity="sha512-yHknP1/AwR+yx26cB1y0cjvQUMvEa2PFzt1c9LlS4pRQ5NOTZFWbhBig+X9G9eYW/8m0/4OXNx8pxJ6z57x0dw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css" integrity="sha512-17EgCFERpgZKcm0j0fEq1YCJuyAWdz9KUtv1EjVuaOz8pDnh/0nZxmU6BBXwaaxqoi9PQXnRWqlcDB027hgv9A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<!-- 	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css.map">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css.map"> -->
	<link rel="stylesheet" href="{% static 'css/bootstrap-grid.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/air-datepicker.css' %}">
	<script src="{% static 'js/air-datepicker.js' %}"></script>
	<link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
	<section id="mobMenu">
			<div class="mobMenu accMenu">
				<div class="container">
				<div class="mobMenu__header">
					<div class="row">
						<div class="col-4 col-md-3">
							<a href="/">
								<img src="{% static 'img/Logo.svg' %}" alt="Logo" class="logo header__logo">
							</a>
						</div>
						<div class="col-3 col-md-2">
							<img src="{% static 'img/x.svg' %}" alt="x" class="mobMenuClose">
						</div>
					</div>
				</div>
				<div class="mobMenu__content">
					<div class="row">
						<div class="col-md-3">
							<nav>
								<div class="accaunt__left">
							<div class="accaunt__ava fic">
								<img src="{% static 'img/avatars/1.svg' %}" alt="avatar" class="accaunt__ava_img">
								<span class="accaunt__ava_name">Алиса И.</span>
							</div>
							<div class="accaunt__settings fic">
								<a href="#" class="accaunt__settings_intro">Изменить профиль</a>
								<a href="#" class="accaunt__settings_out">Выйти</a>
							</div>
							<nav>
								<div class="accaunt__menu_title">МЕНЮ</div>
								<ul class="accaunt__menu">
									<li class="accaunt__menu_item active">
										<a href="#" class="accaunt__menu_item__link">
											<div class="accaunt__menu_block fic">
												<img src="{% static 'img/icons/list.svg' %}" alt="icon" class="accaunt__menu_icon">
												<span class="accaunt__menu_item__link_intro">Мои записи</span>
											</div>
										</a>
									</li>
									<li class="accaunt__menu_item">
										<a href="#" class="accaunt__menu_item__link">
											<div class="accaunt__menu_block fic">
												<img src="{% static 'img/icons/settings.svg' %}" alt="icon" class="accaunt__menu_icon">
												<span class="accaunt__menu_item__link_intro">Настройки</span>
											</div>
										</a>
									</li>
									<li class="accaunt__menu_item">
										<a href="#" class="accaunt__menu_item__link">
											<div class="accaunt__menu_block fic">
												<img src="{% static 'img/icons/tex.svg' %}" alt="icon" class="accaunt__menu_icon">
												<span class="accaunt__menu_item__link_intro">Тех. поддержка</span>
											</div>
										</a>
									</li>
									<li class="accaunt__menu_item">
										<a href="#" class="accaunt__menu_item__link">
											<div class="accaunt__menu_block fic">
												<img src="{% static 'img/icons/pay.svg' %}" alt="icon" class="accaunt__menu_icon">
												<span class="accaunt__menu_item__link_intro">Платежи</span>
											</div>
										</a>
									</li>
								</ul>
							</nav>
						</div>
							</nav>
							<nav>
								<ul class="mobMenu__menu">
									<li class="mobMenu__menu_item">
										<a href="#" class="mobMenu__menu_link">Мастера</a>
									</li>
									<li class="mobMenu__menu_item"><a href="#" class="mobMenu__menu_link">Услуги</a></li>
									<li class="mobMenu__menu_item"><a href="#" class="mobMenu__menu_link">Отзывы</a></li>
									<li class="mobMenu__menu_item"><a href="#" class="mobMenu__menu_link">Контакты</a></li>
								</ul>
							</nav>
							<a href="#" class="mobMenu__account">Личный кабинет</a>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<button class="mobMenu__btn">Перезвоните мне</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<header id="header">
		<div class="container">
			<div class="header">
				<div class="row">
					<div class="col-2 col-md-2 mob">
						<img src="{% static 'img/hamburger.svg' %}" alt="hamburger" class="header__mobMenu">
					</div>
					<div class="col-5 col-md-3 col-lg-2">
						<a href="/">
							<img src="{% static 'img/Logo.svg' %}" alt="Logo" class="logo header__logo">
						</a>
					</div>
					<div class="col-md-5 ">
						<nav>
						<ul class="menu">
							<li class="menu__item"><a href="#" class="menu__item_link">Мастера</a></li>
							<li class="menu__item"><a href="#" class="menu__item_link">Услуги</a></li>
							<li class="menu__item"><a href="#" class="menu__item_link">Отзывы</a></li>
							<li class="menu__item"><a href="#" class="menu__item_link">Контакты</a></li>
						</ul>
					</nav>
					</div>
					<div class="col-2 col-md-2 col-lg-3">
						<div class="header__block">
						<button class="header__block_btn">Перезвоните мне</button>
						<div class="header__block_auth">
							<img src="{% static 'img/avatars/1.svg' %}" alt="account" class="header__account_img">
							<!-- <span class="header__block_auth__intro">Алиса И.</span> -->
						</div>
					</div>
					</div>
				</div>



			</div>
		</div>
	</header>
	<section id="admin">
		<div class="container">
			<div class="admin">
				<div class="row">
					<div class="col-md-2 dec">
						<div class="accaunt__left">
							<div class="accaunt__ava fic">
								<img src="{% static 'img/avatars/1.svg' %}" alt="avatar" class="accaunt__ava_img">
								<span class="accaunt__ava_name">Администратор</span>
							</div>
							<div class="accaunt__settings fic">
								<a href="#" class="accaunt__settings_intro">Изменить профиль</a>
								<a href="#" class="accaunt__settings_out">Выйти</a>
							</div>
							<nav>
								<div class="accaunt__menu_title">МЕНЮ</div>
								<ul class="accaunt__menu">
									<li class="accaunt__menu_item active">
										<a href="#" class="accaunt__menu_item__link">
											<div class="accaunt__menu_block fic">
												<img src="{% static 'img/icons/list.svg' %}" alt="icon" class="accaunt__menu_icon">
												<span class="accaunt__menu_item__link_intro">Мои записи</span>
											</div>
										</a>
									</li>
									<li class="accaunt__menu_item">
										<a href="#" class="accaunt__menu_item__link">
											<div class="accaunt__menu_block fic">
												<img src="{% static 'img/icons/settings.svg' %}" alt="icon" class="accaunt__menu_icon">
												<span class="accaunt__menu_item__link_intro">Настройки</span>
											</div>
										</a>
									</li>
									<li class="accaunt__menu_item">
										<a href="#" class="accaunt__menu_item__link">
											<div class="accaunt__menu_block fic">
												<img src="{% static 'img/icons/tex.svg' %}" alt="icon" class="accaunt__menu_icon">
												<span class="accaunt__menu_item__link_intro">Тех. поддержка</span>
											</div>
										</a>
									</li>
									<li class="accaunt__menu_item">
										<a href="#" class="accaunt__menu_item__link">
											<div class="accaunt__menu_block fic">
												<img src="{% static 'img/icons/pay.svg' %}" alt="icon" class="accaunt__menu_icon">
												<span class="accaunt__menu_item__link_intro">Платежи</span>
											</div>
										</a>
									</li>
								</ul>
							</nav>
						</div>
					</div>
					<div class="col-md-9">
						<div class="admin__main">
							<div class="admin__title">Главная</div>
							<hr class="hr">
							<div class="admin__main_block">
								<div class="admin__main_block__items">
									<div class="admin__main_monthPrise admin__main_block__elem">
										<div class="admin__main_monthPrise__intro">Сумма оплат за месяц</div>
										<div class="admin__main_monthPrise__sum">628 200 рублей</div>
									</div>
									<div class="admin__main_block__elem">
										<div class="admin__main_monthPrise__intro">Посещений за месяц</div>
										<div class="admin__main_monthPrise__sum">349</div>
									</div>
								</div>
								<div class="admin__main_block__items">
									<div class="admin__main_block__elem">
										<div class="admin__main_monthPrise__intro">Посещений за месяц</div>
										<div class="admin__main_monthPrise__sum">349</div>
									</div>
									<div class="admin__main_block__elem">
										<div class="admin__main_monthPrise__intro">Процент посещений</div>
										<div class="admin__main_monthPrise__circle">100%</div>
									</div>
									<div class="admin__main_block__elem">
										<div class="admin__main_monthPrise__intro">Посещений за год</div>
										<div class="admin__main_monthPrise__sum">3 956</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<footer id="footer">
		<div class="container">
			<div class="footer">
				<div class="footer__block">
					<div class="row">
						<div class="col-md-3 col-lg-2">
							<a href="/"><img src="{% static 'img/Logo.svg' %}" alt="logo" class="footer__logo"></a>
						</div>
						<div class="col-md-5 minMobHide">
							<nav>
								<ul class="menu">
									<li class="menu__item"><a href="#" class="menu__item_link">Мастера</a></li>
									<li class="menu__item"><a href="#" class="menu__item_link">Услуги</a></li>
									<li class="menu__item"><a href="#" class="menu__item_link">Отзывы</a></li>
									<li class="menu__item"><a href="#" class="menu__item_link">Контакты</a></li>
								</ul>
							</nav>
						</div>
					</div>
					<div class="footer__contact">
						<div class="row">
							<div class="col-md-4">

									<div class="footer__data">с 10:00 до 20:00  без выходных</div>

							</div>
							<div class="col-md-3">
								<a href="tel:+79179023800" class="contacts__info_tel">+7 (917) 902 38 00</a>
							</div>
						</div>
						<div class="row">
							<div class="col-md-5 minMobShow">
								<nav>
									<ul class="menu">
										<li class="menu__item"><a href="#" class="menu__item_link">Мастера</a></li>
										<li class="menu__item"><a href="#" class="menu__item_link">Услуги</a></li>
										<li class="menu__item"><a href="#" class="menu__item_link">Отзывы</a></li>
										<li class="menu__item"><a href="#" class="menu__item_link">Контакты</a></li>
									</ul>
								</nav>
							</div>
						</div>
					</div>
					<hr class="hr"></hr>
					<div class="footer__bottom">
						<div class="row">
							<div class="col-md-4 col-lg-3">
								<a href="#" class="footer__link">Политика конфиденциальности</a>
							</div>
							<div class="col-md-3">
								<div class="footer__copy">2022. Все права защищены</div>
							</div>
							<div class="col-md-3 col-lg-2">
								<div class="footer__social fic">
									<a href=""><img src="{% static 'img/waGray.svg' %}" alt="wa" class="contacts__social_icon"></a>
									<a href=""><img src="{% static 'img/vkGray.svg' %}" alt="vk" class="contacts__social_icon"></a>
									<a href=""><img src="{% static 'img/tgGray.svg' %}" alt="tg" class="contacts__social_icon"></a>
									<a href=""><img src="{% static 'img/instaGray.svg' %}" alt="insta" class="contacts__social_icon"></a>
								</div>
							</div>
						</div>



					</div>

				</div>
			</div>
		</div>
	</footer>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js" integrity="sha512-aVKKRRi/Q/YV+4mjoKBsE4x3H+BkegoM/em46NNlCqNTmUYADjBbeNefNxYV7giUp0VxICtqdrbqU7iVaeZNXA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js" integrity="sha512-XtmMtDEcNz2j7ekrtHvOVR4iwwaD6o/FUJe6+Zq+HgcCsk3kj4uSQQR8weQ2QVj1o0Pk6PwYLohm206ZzNfubg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

	<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/popup.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
	<div class="authPopup popup">
		<div class="popup__title authPopup__title">Войти по коду</div>
		<p class="popup__text authPopup__text">Введите свой номер телефона, мы вышлем на него код</p>
		<form action="#" class="authPopup__form">
			<div class="contacts__form_inputBlock">
				<input type="text" name="tel" class="contacts__form_iunput" placeholder="+7(999)999--99-99" required="">
			</div>
			<div class="contacts__form_checkboxBlock fic">
				<input type="checkbox" class="contacts__form_checkbox" checked="">
				<span class="contacts__form_checkboxBlock__intro">Я согласен(а) с политикой конфидециоальности</span>
			</div>
			<button type="submit" class="popup__btn authPopup__btn">Отправить</button>
		</form>
	</div>

	<div class="confirmPopup popup">
		<div class="popup__title confirmPopup__title">Подтвердите номер</div>
		<p class="popup__text confirmPopup__text">Введите код, полученный по SMS на номер +7 (928) 164 48 60</p>
		<div class="confirmPopup__number">
			<input type="text" name="num1" class="tipsPopup__form_inputNum popup__input" placeholder="" required>
			<input type="text" name="num2" class="tipsPopup__form_inputNum popup__input" placeholder="" required>
			<input type="text" name="num3" class="tipsPopup__form_inputNum popup__input" placeholder="" required>
			<input type="text" name="num4" class="tipsPopup__form_inputNum popup__input" placeholder="" required>

		</div>
		<div class="confirmPopup__sms">Если SMS не пришло вы можете <a href="#" class="popup__link">запросить код повторно</a></div>
		<div class="confirmPopup__changeNumber">
			<a href="#" class="confirmPopup__link popup__link">Изменить номер телефона</a>
		</div>
	</div>

	<div class="tipsPopup popup">
		<div class="popup__title tipsPopup__title">Чаевые</div>
		<form action="#" class="tipsPopup__form">
			<div class="tipsPopup__form_intro popup__intro">Введите сумму чаевых</div>
			<input type="text" class="tipsPopup__form_input popup__input" placeholder="0.00" required>
			<button class="tipsPopup__btn popup__btn">Далее</button>
		</form>
	</div>

	<div class="paymentPopup popup">
		<div class="popup__title paymentPopup__title">Оплата</div>
		<form action="#" class="paymentPopup__form">
			<div class="paymentPopup__form_intro popup__intro">номер карты</div>
			<input type="text" name="tel" class="paymentPopup__form_input popup__input" placeholder="Введите номер" required>
			<div class="paymentPopup__form_block fic">
				<input type="text" name="mm" class="tipsPopup__form_inputMin popup__input" placeholder="ММ" required>
				<input type="text" name="gg" class="tipsPopup__form_inputMin popup__input" placeholder="ГГ" required>
			</div>
			<div class="paymentPopup__form_elems fic">
				<input type="text" name="fname" class="paymentPopup__form_inputMid popup__input" placeholder="Имя владельца" required>
				<input type="text" name="cvc" class="tipsPopup__form_inputMin popup__input" placeholder="CVC" required>
			</div>
			<div class="paymentPopup__form_intro popup__intro">Ваш e-mail(необязательно)</div>
			<input type="email" name="tel" class="paymentPopup__form_input popup__input" placeholder="pochta@mail.ru">
			<button class="tipsPopup__btn popup__btn">Оплатить</button>
		</form>
	</div>

	<div class="reviewPopup popup">
		<div class="popup__title reviewPopup__title">Отзыв</div>
		<form action="#" class="reviewPopup__form">
			<input type="text" name="fname" class="paymentPopup__form_input popup__input" placeholder="Введите имя" required>
			<div class="contacts__form_inputBlock">
				<input type="text" name="tel" class="contacts__form_iunput" placeholder="+7(999)999--99-99" required="">
			</div>
			<input type="text" name="dateVis" class="paymentPopup__form_input popup__input" placeholder="Дата посещения" required>
			<textarea name="popupTextarea" class="reviewPopup__form_textarea" placeholder="Текст отзыва"></textarea>
			<div class="contacts__form_checkboxBlock fic">
				<input type="checkbox" class="contacts__form_checkbox" checked>
				<span class="contacts__form_checkboxBlock__intro">Я согласен(а) с политикой конфидециоальности</span>
			</div>
			<button class="tipsPopup__btn popup__btn">Оплатить</button>
		</form>
	</div>
</body>
</html>

templates/reg_err.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="author" content="CodeHim">
  <title> Ошибка регистрации </title>
  <link rel="stylesheet" href="{% static '/css/style_reg.css' %}">

</head>
<body>
<main class="cd__main">
  <div id='card' class="animated fadeIn">
    <div id='upper-side-err'>
      <h3 id='status'>
        Ошибка
      </h3>
    </div>
    <div id='lower-side'>
      <p id='message'>
        Ошибка регистрации! Проверьте введенные данные!
      </p>
      <a href="{% url 'account:registration' %}" id="contBtn-err">Продолжить</a>
    </div>
  </div>
</main>
</body>
</html>

templates/reg_succ.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="author" content="CodeHim">
  <title> Успешная регистрация </title>
  <link rel="stylesheet" href="{% static '/css/style_reg.css' %}">
</head>
<body>
<main class="cd__main">
  <div id='card' class="animated fadeIn">
    <div id='upper-side-succ'>
      <h3 id='status'>
        Успешно
      </h3>
    </div>
    <div id='lower-side'>
      <p id='message'>
        Спасибо, за регистрацию! Авторизуйтесь по номеру телефона на главной странице сайта
      </p>
      <a href="{% url 'start_page' %}" id="contBtn-succ">Продолжить</a>
    </div>
  </div>
</main>
</body>
</html>

templates/registration.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Регистрация</title>
	<link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
<div class="reviewPopup popup_reg">
		<div class="popup__title reviewPopup__title">Регистрация</div>
  
		<form action="/api/reg/" method="post" class="reviewPopup__form">
      {% csrf_token %}
			<input type="text" name="firstname" class="paymentPopup__form_input popup__input" placeholder="Введите имя" required>
      <input type="text" name="lastname" class="paymentPopup__form_input popup__input" placeholder="Введите фамилию" required>
			<div class="contacts__form_inputBlock">
				<input type="tel" name="phonenumber" class="contacts__form_iunput" placeholder="+7(999)999--99-99" required>
			</div>
			<div class="contacts__form_checkboxBlock fic">
				<input type="checkbox" name="agree" class="contacts__form_checkbox" checked required>
				<span class="contacts__form_checkboxBlock__intro">Я согласен(а) с политикой конфидециоальности</span>
			</div>
			<button class="tipsPopup__btn popup__btn">Зарегистрироваться</button>
		</form>
	</div>
</body>